### ISSUE TITLE
Should mention the transient nature of Keystore based keys

### ISSUE THREAD

**Issue by doridori** [iamMehedi/Secured-Preference-Store#1]
Docs should mention this as there are a few cases where using your lib will result in irretrievable data http://doridori.github.io/android-security-the-forgetful-keystore/

**Comment by iamMehedi** [comment]
@doridori Yeah thought of that! Will add that in the docs as soon as I can.

**Comment by iamMehedi** [comment]
@doridori Updated the docs with a link to your blog.
