### ISSUE TITLE
Use Github Release Structure or CHANGELOG

### ISSUE THREAD

**Issue by StuStirling** [iamMehedi/Secured-Preference-Store#16]
It would be useful to have a CHANGELOG.md in the project's root or to use Github's release tagging feature to keep track of the different changes between versions.

For example the recent addition of the init method is a breaking change and would be useful if it was more obvious that it was added.

**Comment by iamMehedi** [comment]
Release tags work better in my opinion.

**Comment by iamMehedi** [comment]
tag v0.5.0 has been added.
