### ISSUE TITLE
Remove sharedPreferences

### ISSUE THREAD

**Issue by fermedina** [iamMehedi/Secured-Preference-Store#19]
Hi!

How can I remove my sharedPreferences?

**Comment by iamMehedi** [comment]
Just the way you'd remove values from the standard SharedPreferences:
https://stackoverflow.com/questions/8034127/how-to-remove-some-key-value-pair-from-sharedpreferences

**Comment by fermedina** [comment]
But I would like remove a specific entry. I have seen that the keys are encrypted and I don’t know how to remove the key that I would like. Can you help me?

**Comment by iamMehedi** [comment]
As you don't provide hashed key to store or retrieve a value, you don't need to provide the hashed key for removing a value. Just provide the actual key and the library will handle hashing it appropriately.

**Comment by fermedina** [comment]
But the library doesn't have any method to remove a key/value pair. I want to remove all key/value pair except one. But I don't know how to know which key/value pair doesn't remove, because te key is also encrypted

**Comment by iamMehedi** [comment]
`SecuredPreferenceStore` is a `SharedPreferences` implementation hence has all the methods that a `SharedPreferences` is supposed to have and behaves similarly.

to remove a `key` and associated value call:
```java
SecuredPreferenceStore prefStore = SecuredPreferenceStore.getSharedInstance(getApplicationContext());
prefStore.edit().remove("key").apply();
```
