### ISSUE TITLE
Some help would be appreciated

### ISSUE THREAD

**Issue by gnoriega27** [iamMehedi/Secured-Preference-Store#28]
I'm kind of new at android development and would love some guidance if possible. I was wondering why when I add

`compile 'online.devliving:securedpreferencestore:latest_version'`

and build, I get this error:

`Failed to resolve: online`

Thanks in advance

**Comment by ebabel** [comment]
@gnoriega27 "latest_version" means you need to figure out what the latest version is.
use this instead
`implementation 'online.devliving:securedpreferencestore:0.6.0'`
or
`implementation 'online.devliving:securedpreferencestore:0.5.0'`
