### ISSUE TITLE
AndroidManifest contains application label

### ISSUE THREAD

**Issue by karolzdebel** [iamMehedi/Secured-Preference-Store#43]
Secured-Preference-Store/securedpreferencestore/src/main/AndroidManifest.xml
`    <application
        android:label="@string/app_name">`

The AndroidManifest in the SecuredPreferenceStore package contains an application label which causes a Manifest merger failure for any project which also contains its own label. What is the purpose of this labels presence? 

Adding tools:replace to the Android Manifest is not a solution for me since this library is being integrated into an SDK and I do not want to force everyone using it to have to add this as well. 

Error: Manifest merger failed : Attribute application@label value=(My Application) from AndroidManifest.xml:14:9-39
    is also present at [online.devliving:securedpreferencestore:0.7.4] AndroidManifest.xml:11:18-50 value=(@string/app_name).
    Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:10:5-40:19 to override.

**Comment by karolzdebel** [comment]
Addressed in PR: https://github.com/iamMehedi/Secured-Preference-Store/pull/44, just needs to be approved.

**Comment by iamMehedi** [comment]
PR #44 has been merged.
